### ISSUE TITLE
Unsupported operant types running php cli_install.php

### ISSUE THREAD

**Issue by jmpolvera** [flyve-mdm/glpi-plugin#496]
**Describe the bug**
After performing a git pull in order to update and run php /tools/cli_install.php I get the following error.

**PHP Fatal error:  Uncaught Error: Unsupported operand types in /var/www/glpi/plugins/flyvemdm/install/installer.class.php:261**

**To Reproduce**
1. Go to 'plugins/flyvemdm'
2. perform git pull
3. run php tools/cli_install.php

**Expected behavior**
command exit with no errors

**Screenshots**
PHP Warning:  Module 'apcu' already loaded in Unknown on line 0
  From Config::getCache() in /var/www/glpi/inc/config.class.php line 2813
  Service with name "Zend\Cache\Storage\Adapter\Apcu" could not be created. Reason: ext/apcu is disabled - see 'apc.enabled' and 'apc.enable_cli'
Installing Plugin Id: 1 version 2.0.0-dev
**PHP Fatal error:  Uncaught Error: Unsupported operand types in /var/www/glpi/plugins/flyvemdm/install/installer.class.php:261**
Stack trace:
#0 /var/www/glpi/plugins/flyvemdm/install/installer.class.php(129): PluginFlyvemdmInstaller->createFirstAccess()
#1 /var/www/glpi/plugins/flyvemdm/hook.php(41): PluginFlyvemdmInstaller->install()
#2 /var/www/glpi/inc/plugin.class.php(731): plugin_flyvemdm_install()
#3 /var/www/glpi/plugins/flyvemdm/tools/cli_install.php(137): Plugin->install('1')
#4 {main}
  thrown in /var/www/glpi/plugins/flyvemdm/install/installer.class.php on line 261

**Desktop (please complete the following information):**
 - Flyvemdm version 2.0.0-dev
 - Fusion inventory version : 9.2+1.0
 - GLPI 9.2.2

**Comment by btry** [comment]
Hi I'm suspecting that one of the operands is not an array and the other is an array when the error occurred.

**Comment by btry** [comment]
My theory may be good
```
$ php -a
Interactive mode enabled

php > var_dump(null + ['a']);
PHP Fatal error:  Unsupported operand types in php shell code on line 1
```
