### ISSUE TITLE
Unit tests might fail in some condition

### ISSUE THREAD

**Issue by btry** [flyve-mdm/glpi-plugin#601]
**Describe the bug**
An issue in unit tests:
```
> There is 1 error:
=> tests\units\PluginFlyvemdmPolicyDeployfile::testConflictCheck():
==> Error UNKNOWN in /home/travis/build/flyve-mdm/glpi/plugins/flyvemdm/tests/suite-unit/PluginFlyvemdmPolicyDeployfile.php on unknown line, generated by unknown file:
Fatal error: Uncaught Error: Call to a member function getID() on null in /home/travis/build/flyve-mdm/glpi/plugins/flyvemdm/tests/suite-unit/PluginFlyvemdmPolicyDeployfile.php:247
Stack trace:
#0 /home/travis/build/flyve-mdm/glpi/plugins/flyvemdm/vendor/atoum/atoum/classes/test.php(1363): tests\units\PluginFlyvemdmPolicyDeployfile->testConflictCheck()
#1 Standard input code(1): mageekguy\atoum\test->runTestMethod('testConflictChe...')
#2 {main}
  thrown in /home/travis/build/flyve-mdm/glpi/plugins/flyvemdm/tests/suite-unit/PluginFlyvemdmPolicyDeployfile.php on line 247
uncompleted
> There is 1 uncompleted method:
=> tests\units\PluginFlyvemdmPolicyDeployfile::testConflictCheck() with exit code 255:
==> output(153) "CommonDBTM::getFromDBByCrit() in /home/travis/build/flyve-mdm/glpi/inc/commondbtm.class.php line 251
==> getFromDBByCrit expects to get one result, 2 found!"
> Total tests duration: 5.26 seconds.
> Total tests memory usage: 91.23 Mb.
> Running duration: 17.66 seconds.
```
**To Reproduce**
There is maybe a race condition when unit tests run in parallel

**Comment by DIOHz0r** [comment]
I'm also getting this error for other tests...

```
  *** MySQL query error:
  SQL: INSERT INTO `glpi_plugin_fusioninventory_dblocksoftwares`
               SET `value`='1'
  Error: Duplicate entry '1' for key 'PRIMARY'
  Backtrace :
  ...ventory/inc/inventorycomputerlib.class.php:2509 
  ...nventory/inc/inventorycomputerlib.class.php:822 PluginFusioninventoryInventoryComputerLib->importSoftware()
  ...ry/inc/inventorycomputerinventory.class.php:560 PluginFusioninventoryInventoryComputerLib->updateComputer()
  ...inventory/inc/inventoryruleimport.class.php:815 PluginFusioninventoryInventoryComputerInventory->rulepassed()
  inc/rule.class.php:1436                            PluginFusioninventoryInventoryRuleImport->executeActions()
  inc/rulecollection.class.php:1461                  Rule->process()
  ...ry/inc/inventorycomputerinventory.class.php:361 RuleCollection->processAllRules()
  ...ry/inc/inventorycomputerinventory.class.php:126 PluginFusioninventoryInventoryComputerInventory->sendCriteria()
  ...fusioninventory/inc/communication.class.php:235 PluginFusioninventoryInventoryComputerInventory->import()
  ...fusioninventory/inc/communication.class.php:463 PluginFusioninventoryCommunication->import()
  plugins/flyvemdm/inc/agent.class.php:1271          PluginFusioninventoryCommunication->handleOCSCommunication()
  plugins/flyvemdm/inc/agent.class.php:451           PluginFlyvemdmAgent->enrollByInvitationToken()
  inc/commondbtm.class.php:891                       PluginFlyvemdmAgent->prepareInputForAdd()
  .../tests/src/Flyvemdm/Tests/CommonTestCase.php:60 CommonDBTM->add()
  ...tests/src/Flyvemdm/Tests/CommonTestCase.php:189 Flyvemdm\Tests\CommonTestCase->enrollFromInvitation()
  ...dm/tests/suite-unit/PluginFlyvemdmAgent.php:255 Flyvemdm\Tests\CommonTestCase->createAgent()
  ...yvemdm/vendor/atoum/atoum/classes/test.php:1363 tests\units\PluginFlyvemdmAgent->testGetAgents()
  .../atoum/atoum/classes/test/engines/inline.php:43 mageekguy\atoum\test->runTestMethod()
  ...yvemdm/vendor/atoum/atoum/classes/test.php:1918 mageekguy\atoum\test\engines\inline->run()
  ...yvemdm/vendor/atoum/atoum/classes/test.php:1827 mageekguy\atoum\test->runEngine()
  ...yvemdm/vendor/atoum/atoum/classes/test.php:1477 mageekguy\atoum\test->runEngines()
  ...vemdm/vendor/atoum/atoum/classes/runner.php:597 mageekguy\atoum\test->run()
  ...dor/atoum/atoum/classes/scripts/runner.php:1270 mageekguy\atoum\runner->run()
  ...vemdm/vendor/atoum/atoum/classes/script.php:281 mageekguy\atoum\scripts\runner->doRun()
  .../atoum/atoum/classes/script/configurable.php:80 mageekguy\atoum\script->run()
  ...ndor/atoum/atoum/classes/scripts/runner.php:214 mageekguy\atoum\script\configurable->run()
  ...ndor/atoum/atoum/classes/scripts/runner.php:702 mageekguy\atoum\scripts\runner->run()
  :                                                  mageekguy\atoum\scripts\runner::mageekguy\atoum\scripts\{closure}()
```

**Comment by btry** [comment]
Tests which use inventory import from Fusion don't give use many choices. The only way is to run them inline.

**Comment by btry** [comment]
@DIOHz0r your report might be solved by #604. Have a look and tell what you think about it.

**Comment by btry** [comment]
this failure occurs quite often
```
There is 1 exception:
=> tests\units\PluginFlyvemdmPolicyDeployapplication::testUnicityCheck():
==> An exception has been thrown in file /home/travis/build/flyve-mdm/glpi/plugins/flyvemdm/tests/suite-unit/PluginFlyvemdmPolicyDeployapplication.php on line 128:
==> RuntimeException: CommonDBTM::getFromDBByCrit() in /home/travis/build/flyve-mdm/glpi/inc/commondbtm.class.php line 289
==> getFromDBByCrit expects to get one result, 2 found!  in /home/travis/build/flyve-mdm/glpi/inc/toolbox.class.php:438
==> Stack trace:
==> #0 /home/travis/build/flyve-mdm/glpi/inc/toolbox.class.php(462): Toolbox::log(Object(Monolog\Logger), 300, Array)
==> #1 /home/travis/build/flyve-mdm/glpi/inc/commondbtm.class.php(289): Toolbox::logWarning('getFromDBByCrit...')
==> #2 /home/travis/build/flyve-mdm/glpi/plugins/flyvemdm/tests/src/Flyvemdm/Tests/CommonTestCase.php(526): CommonDBTM->getFromDBByCrit(Array)
==> #3 /home/travis/build/flyve-mdm/glpi/plugins/flyvemdm/tests/suite-unit/PluginFlyvemdmPolicyDeployapplication.php(128): Flyvemdm\Tests\CommonTestCase->createDummyPackage(0)
==> #4 /home/travis/build/flyve-mdm/glpi/plugins/flyvemdm/vendor/atoum/atoum/classes/test.php(1363): tests\units\PluginFlyvemdmPolicyDeployapplication->testUnicityCheck()
==> #5 Standard input code(1): mageekguy\atoum\test->runTestMethod('testUnicityChec...')
==> #6 {main}
```
